kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: podpreset-webhook
subjects:
  - kind: ServiceAccount
    name: podpreset-webhook
    namespace: podpreset-webhook
roleRef:
  kind: Role
  name: podpreset-webhook
  namespace: podpreset-webhook
  apiGroup: rbac.authorization.k8s.io
